import 'package:workwith_admin/src/features/add_venue/domain/venue_model.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

/// Auth
class EmailNotConfirmedException extends AppException {
  EmailNotConfirmedException()
      : super('email-not-confirmed',
            "Please confirm your email before pressing Continue");
}

class InvalidCredentialsException extends AppException {
  InvalidCredentialsException()
      : super('invalid-credentials', "The email or password is incorrect");
}

class NoImagePathsException extends AppException {
  NoImagePathsException({required Venue venue})
      : super('no-image-paths',
            "Image paths were not found for venue: id: ${venue.id}, name: ${venue.name}");
}

class UserNotAdminException extends AppException {
  UserNotAdminException()
      : super('user-not-admin', "Only admin users can use this app");
}

class LocationPermissionException {}

class LocationServiceDisabledCustomException extends AppException
    implements LocationPermissionException {
  LocationServiceDisabledCustomException()
      : super('location-service-disabled',
            "Please enable location services in your device settings and then reload");
}

class LocationPermissionDeniedCustomException extends AppException
    implements LocationPermissionException {
  LocationPermissionDeniedCustomException()
      : super('location-permission-denied',
            "Please allow permission for this app to access location in your device settings and then reload");
}

class LocationPermissionDeniedForeverCustomException extends AppException
    implements LocationPermissionException {
  LocationPermissionDeniedForeverCustomException()
      : super('location-permission-denied-forever',
            "Please allow permission for this app to access location in your device settings and then reload");
}
